name: 'Microblog-Action'
author: Emanuel Kluge
description: 'Create a microblog from Github issues'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  repo-token:
    description: 'Github Access Token'
    required: true
  url:
    description: 'Full site URL including base path if it exists.'
    required: true
  title:
    description: 'Title of the Microblog'
    required: false
  description:
    description: 'Description of the Microblog'
    required: false
  theme:
    description: 'Theme of the Microblog'
    required: false
    default: 'new.css'
  date-format:
    description: 'Date format based on https://date-fns.org/v2.10.0/docs/format'
    required: false
    default: 'd.M.yyyy H:mm'
  posts-per-page:
    description: 'Amount of posts per page'
    required: false
    default: 10
  custom-styles:
    description: 'Path to a CSS file with custom styles relative to the repo root'
    required: false
  pages:
    description: 'A glob or a list of globs pointing to markdown files which will be rendered as
    static pages'
    required: false
    default: 'pages/*.md'
  static-frontpage:
    description: "Set the microblog's frontpage to be one of the static pages"
    required: false
  label:
    description: 'Only publish issues with a certain label'
    required: false
  closed:
    description: 'Only publish closed issues'
    required: false
  out-dir:
    description: 'Path of the output folder for the rendered site relative to the repo root'
    required: false
    default: '_site'
  static-dir:
    description: 'Path of the static folder relative to the repo root'
    required: false
    default: 'static'
  lang:
    description: 'Language of the Microblog'
    required: false
    default: 'en'
  i18n.next:
    description: 'Label of "next"-link'
    required: false
    default: 'next'
  i18n.prev:
    description: 'Label of "prev"-link'
    required: false
    default: 'previous'
  i18n.posts:
    description: 'Label of "Posts"-link'
    required: false
    default: 'Posts'
runs:
  using: 'node12'
  main: 'dist/index.js'
